name: Crypto Patrol Ultimate

on:
  schedule:
    # Jalan setiap 2 jam sekali (Ganti angka '*/2' jika mau tiap jam)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Tombol manual buat tes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode
        uses: actions/checkout@v2

      - name: Siapkan Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Library
        run: |
          pip install -r requirements.txt

      - name: Jalankan Misi
        env:
          # Mengambil rahasia dari Setting GitHub (Biar Tokenmu aman)
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
